from teams.models import Team, State, Sex, Category, Region
from users.models import Coach, Player
from tournaments.models import Tournament, Day, Game, Venue, Point, Foul, Win, Quarter
from django.utils import timezone
from django.contrib.auth.models import User
State.objects.all().delete()
Team.objects.all().delete()
Coach.objects.all().delete()
Day.objects.all().delete()
Venue.objects.all().delete()
Tournament.objects.all().delete()
Game.objects.all().delete()
User.objects.all().delete()
User.objects.all().delete()
Win.objects.all().delete()

m = Sex.objects.create(name="Masculine")
f = Sex.objects.create(name="Feminine")
u15 = Category.objects.create(name='U-15')
u17 = Category.objects.create(name='U-17')
u19 = Category.objects.create(name='U-19')
s = State.objects.create(name="Prueba", code="PRB")
s.save()
s2 = State.objects.create(name="Prueba2", code="PRB2")
s2.save()
r = Region.objects.create(name="PruebaR", code="PRBR")
r.state_set.add(s)
r.state_set.add(s2)
t1 = Team.objects.create(sex=f, category=u15, state=s, address="addprueba1", name="teamprueba1")
t1.save()
t1.generate_code()
t2 = Team.objects.create(sex=f, category=u15, state=s, address="addprueba2", name="teamprueba2")
t2.save()
t2.generate_code()
t3 = Team.objects.create(sex=f, category=u15, state=s2, address="addprueba3", name="teamprueba3")
t3.save()
t3.generate_code()
tour = Tournament.objects.create(is_active=True, sex=f, category=u15, name="tourprueba", start_date=timezone.now())
tour.save()
tour.team_set.add(t1)
tour.team_set.add(t2)
tour.team_set.add(t3)
tour.save()
day = Day.objects.create(number=1, is_inter_zone=False, start_date=timezone.now(), end_date=timezone.now() + timezone.timedelta(days=1), tournament=tour)
day.save()
place = Venue.objects.create(name="venueprueba", courts=3, address="addressvenueprueba", state=s)
place.save()
g1 = Game.objects.create(number=1, date_time=timezone.now(), team_local=t1, team_visitor=t2, court=1, day=day, venue=place)
g1.save()
g2 = Game.objects.create(number=2, date_time=timezone.now()+timezone.timedelta(hours=2), team_local=t1, team_visitor=t2, court=2, day=day, venue=place)
g2.save()
up1 = User.objects.create_user('p1', 'p1@mail', 'pass')
up2 = User.objects.create_user('p2', 'p2@mail', 'pass')
uc1 = User.objects.create_user('c1', 'c1@mail', 'pass')
uc2 = User.objects.create_user('c2', 'c2@mail', 'pass')
c1 = Coach.objects.create(user=uc1, telephone="1234567890", start_date=timezone.now(), team=t1)
c1.save()
c2 = Coach.objects.create(user=uc2, telephone="1234567890", start_date=timezone.now(), team=t2)
c2.save()
p1 = Player.objects.create(sex=f, user=up1, date_of_birth=timezone.now(), telephone="12345667890", team=t1)
p1.save()
p2 = Player.objects.create(sex=f, user=up2, date_of_birth=timezone.now(), telephone="22345667890", team=t2)
p2.save()
q = Quarter.objects.create(game=g1, number=1)
q2 = Quarter.objects.create(game=g1, number=2)
q3 = Quarter.objects.create(game=g1, number=3)
q4 = Quarter.objects.create(game=g1, number=4)
Point.objects.create(quarter=q, player=p1, value=1)
Point.objects.create(quarter=q, player=p2, value=2)
Point.objects.create(quarter=q2, player=p1, value=1)
Point.objects.create(quarter=q2, player=p2, value=1)
Point.objects.create(quarter=q2, player=p1, value=1)
Point.objects.create(quarter=q2, player=p2, value=1)
Point.objects.create(quarter=q4, player=p1, value=1)
Point.objects.create(quarter=q4, player=p2, value=1)
Point.objects.create(quarter=q4, player=p1, value=1)
Point.objects.create(quarter=q4, player=p2, value=1)
Foul.objects.create(quarter=q, player=p1, type='1')
Foul.objects.create(quarter=q, player=p2, type='1')
g1.finish()
