from teams.models import Team, State
from users.models import Coach, Player
from tournaments.models import Tournament, Day, Game, Venue, Point, Foul
from django.utils import timezone

State.objects.all().delete()
Team.objects.all().delete()
Coach.objects.all().delete()
Day.objects.all().delete()
Venue.objects.all().delete()
Tournament.objects.all().delete()
Game.objects.all().delete()

s = State(1, "Prueba", "PRB")
s.save()

t1 = Team(1, state=s, address="addprueba1", name="teamprueba1")
t1.save()
t2 = Team(2, state=s, address="addprueba2", name="teamprueba2")
t2.save()
c1 = Coach(1, name="Pruebencio", last_names="Pruebez Prueba", telephone="1234567890", email_address="prueba@prueba.com", start_date=timezone.now(), team=t1)
c1.save()
c2 = Coach(2, name="Pruebencio2", last_names="Pruebez2 Prueba2", telephone="1234567892", email_address="prueba2@prueba2.com", start_date=timezone.now(), team=t2)
c2.save()
p1 = Player(1, name="p1", last_names="p1 p1", date_of_birth=timezone.now(), telephone="12345667890", email_address="p1@mail.com", team=t1)
p1.save()
p2 = Player(2, name="p2", last_names="p2 p2", date_of_birth=timezone.now(), telephone="22345667890", email_address="p2@mail.com", team=t2)
p2.save()
tour = Tournament(1, name="tourprueba", start_date=timezone.now())
tour.save()
tour.teams.add(t1)
tour.teams.add(t2)
tour.save()
day = Day(1, number=1, is_inter_zone=False, start_date=timezone.now(), end_date=timezone.now() + timezone.timedelta(days=1), tournament=tour)
day.save()
place = Venue(1, name="venueprueba", courts=3, address="addressvenueprueba", state=s)
place.save()
g1 = Game(1, number=1, date_time=timezone.now(), team_local=t1, team_visitor=t2, court=1, day=day, venue=place)
g1.save()
g2 = Game(2, number=2, date_time=timezone.now()+timezone.timedelta(hours=2), team_local=t1, team_visitor=t2, court=2, day=day, venue=place)
g2.save()
(Point(1, game=g1, player=p1, value=1)).save()
(Point(2, game=g1, player=p2, value=2)).save()
(Foul(1, game=g1, player=p1, type='1')).save()
(Foul(2, game=g1, player=p2, type='1')).save()

