# Generated by Django 2.1.5 on 2019-03-07 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190307_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='city',
            field=models.CharField(default='Temp', max_length=50, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='team',
            name='cede',
            field=models.CharField(max_length=200, verbose_name='Cede'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre de Equipo'),
        ),
        migrations.AlterField(
            model_name='team',
            name='nombre_Coach',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Coach'),
        ),
    ]
