# Generated by Django 2.1.7 on 2019-03-08 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190307_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='nombre_Coach',
        ),
        migrations.AlterField(
            model_name='coach',
            name='end_date',
            field=models.DateTimeField(verbose_name='end_date'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='name',
            field=models.CharField(max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='start_date',
            field=models.DateTimeField(verbose_name='start_date'),
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
