# Generated by Django 2.1.7 on 2019-03-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190308_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='end_date',
            field=models.DateTimeField(null=True, verbose_name='end_date'),
        ),
    ]
