# Generated by Django 2.1.7 on 2019-03-08 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190308_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='email_address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
