# Generated by Django 2.1.7 on 2019-03-08 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_coach_email_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='end_date',
            field=models.DateField(null=True, verbose_name='end_date'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='start_date',
            field=models.DateField(verbose_name='start_date'),
        ),
    ]
