# Generated by Django 2.1.5 on 2019-03-11 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20190311_2147'),
        ('users', '0007_auto_20190308_1719'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coach',
        ),
    ]
