# Generated by Django 2.1.5 on 2019-03-11 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0008_delete_coach'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('last_names', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=100)),
                ('email_address', models.CharField(max_length=100, null=True)),
                ('start_date', models.DateField(verbose_name='start_date')),
                ('end_date', models.DateField(null=True, verbose_name='end_date')),
            ],
        ),
    ]
