# Generated by Django 2.1.7 on 2019-03-08 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='games',
        ),
        migrations.AddField(
            model_name='game',
            name='tournament_id',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='tournaments.Tournament'),
            preserve_default=False,
        ),
    ]
