# Generated by Django 2.1.5 on 2019-03-11 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        ('tournaments', '0002_auto_20190308_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='teamLocal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='LocalTeam', to='teams.Team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='teamVisitante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='VisitanteTeam', to='teams.Team'),
            preserve_default=False,
        ),
    ]
