# Generated by Django 2.1.5 on 2019-03-11 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_auto_20190311_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('end_date', models.DateTimeField(verbose_name='End Date')),
                ('tipo_Jornada', models.CharField(choices=[('IZ', 'InterZonas'), ('Z', 'Zonas')], max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='jornada',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tournaments.Jornada'),
            preserve_default=False,
        ),
    ]
