# Generated by Django 2.1.5 on 2019-03-11 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_auto_20190311_2157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='tournament_id',
            new_name='tournament',
        ),
    ]
