# Generated by Django 2.1.5 on 2019-03-11 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_auto_20190311_2201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('end_date', models.DateTimeField(verbose_name='End Date')),
                ('tipo', models.CharField(choices=[('IZ', 'InterZona'), ('Z', 'Zona')], max_length=2)),
            ],
        ),
    ]
