# Generated by Django 2.1.5 on 2019-03-11 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0007_jornada'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='jornada',
            field=models.ForeignKey(default=20, on_delete=django.db.models.deletion.CASCADE, to='tournaments.Jornada'),
            preserve_default=False,
        ),
    ]
