# Generated by Django 2.1.5 on 2019-03-11 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0009_auto_20190311_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jornada',
            name='tipo',
            field=models.CharField(choices=[('IZ', 'InterZona'), ('Z', 'Zona')], max_length=2),
        ),
    ]
