# Generated by Django 2.1.5 on 2019-03-11 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0010_auto_20190311_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='jornada',
            name='torneo',
            field=models.ForeignKey(default=1000, on_delete=django.db.models.deletion.CASCADE, to='tournaments.Tournament'),
            preserve_default=False,
        ),
    ]
