# Generated by Django 2.1.5 on 2019-03-12 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_auto_20190311_2201'),
        ('tournaments', '0017_game_juego'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cede',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canchas', models.PositiveIntegerField(default=6, verbose_name='Numero de Canchas')),
                ('direccion', models.CharField(max_length=200)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.State')),
            ],
        ),
    ]
