# Generated by Django 2.1.5 on 2019-03-12 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0018_cede'),
    ]

    operations = [
        migrations.AddField(
            model_name='cede',
            name='name',
            field=models.CharField(default='NAN', max_length=200, verbose_name='Nombre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='cede',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tournaments.Cede'),
            preserve_default=False,
        ),
    ]
