# Generated by Django 2.1.7 on 2019-03-08 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_auto_20190308_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('ode', models.CharField(max_length=5, verbose_name='code')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('code', models.CharField(max_length=5, verbose_name='code')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='', max_length=50, verbose_name='city')),
                ('address', models.CharField(max_length=200, verbose_name='address')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('mascot', models.CharField(max_length=50, verbose_name='mascot')),
                ('coach_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Coach')),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.State')),
            ],
        ),
        migrations.AddField(
            model_name='region',
            name='state_set',
            field=models.ManyToManyField(to='teams.State'),
        ),
    ]
