# Generated by Django 2.1.7 on 2019-03-08 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='ode',
            new_name='code',
        ),
    ]
