# Generated by Django 2.1.5 on 2019-03-11 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('last_names', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=100)),
                ('email_address', models.CharField(max_length=100, null=True)),
                ('start_date', models.DateField(verbose_name='start_date')),
                ('end_date', models.DateField(null=True, verbose_name='end_date')),
            ],
        ),
        migrations.RenameField(
            model_name='team',
            old_name='state_id',
            new_name='state',
        ),
        migrations.RemoveField(
            model_name='team',
            name='city',
        ),
        migrations.RemoveField(
            model_name='team',
            name='coach_id',
        ),
        migrations.AddField(
            model_name='team',
            name='coach',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='teams.Coach'),
            preserve_default=False,
        ),
    ]
