# Generated by Django 2.1.5 on 2019-03-11 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_coach'),
        ('teams', '0006_auto_20190311_2157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='state_id',
            new_name='state',
        ),
        migrations.RemoveField(
            model_name='team',
            name='city',
        ),
        migrations.RemoveField(
            model_name='team',
            name='coach_id',
        ),
        migrations.AddField(
            model_name='team',
            name='coach',
            field=models.OneToOneField(default=10000, on_delete=django.db.models.deletion.CASCADE, to='users.Coach'),
            preserve_default=False,
        ),
    ]
